# -*- coding=utf-8 -*-

# Input definitions
DATASET = 'hela_tm_tg'

pathvars:
    star_method = '_2pass_nc'

# Output definitions
def get_final_outputs(wildcards):
    output_files = []
    for _, row in samples.iterrows():
        condition_1 = row['condition_1']
        condition_2 = row['condition_2']
        replicate = row['replicate']
        output_files.append(
            f'results/{DATASET}/bam<star_method>/{condition_1}.{condition_2}.{replicate}.bam.bai'
        )

    return output_files

def get_deseq2_outputs(wildcards):
    return [
        f'results/{DATASET}/deseq2/cluster.pdf',
        f'results/{DATASET}/deseq2/pca.pdf'
    ]


include: 'rules/common.smk'
include: 'rules/fastq_dump.smk'
include: 'rules/trim_adapter.smk'
include: 'rules/star_align.smk'
include: 'rules/generate_bigwig.smk'
include: 'rules/diff_exp.smk'
include: 'rules/junction_stat.smk'
include: 'rules/nanopore.smk'

def get_nanopore_mapping_outputs(wildcards):
    output_files = []
    for _, row in samples.iterrows():
        output_files.append(
            f'results/{DATASET}/bam<star_method>/{row["condition_1"]}.{row["condition_2"]}.{row["replicate"]}.bam.bai'
        )
    return output_files

rule all:
    input: []
