#!/usr/bin/env python3
# -*- coding=utf-8 -*-

import pandas as pd
import re
from argparse import ArgumentParser


def extract_symbol(row):
    return re.sub(r'.*gene_name "(\S*)";.*', r'\1', row['attr'])


def extract_id_and_symbol(row):
    gene_id = re.sub(r'.*gene_id "(\S*)";.*', r'\1', row['attr'])
    gene_name = re.sub(r'.*gene_name "(\S*)";.*', r'\1', row['attr'])
    return gene_id, gene_name


def main(annotation, annotation_type, output_tsv):
    output_df = pd.DataFrame()
    if annotation_type == 'gtf':
        genes_df = pd.read_table(
            annotation,
            header=None,
            comment='#',
            usecols=[2, 8],
            names=['type', 'attr']
        )
        genes_df = genes_df[genes_df['type'] == 'gene'].copy()
        genes_df[['id', 'symbol']] = genes_df.apply(extract_id_and_symbol, axis=1, result_type='expand')
        genes_df.set_index('id', inplace=True, drop=False)
    elif annotation_type == 'bed':
        genes_df = pd.read_table(
            annotation,
            header=None,
            usecols=[3, 9],
            names=['id', 'attr']
        )
        genes_df.set_index('id', inplace=True, drop=False)
        genes_df['symbol'] = genes_df.apply(extract_symbol, axis=1)
    
    output_df = genes_df[['id','symbol']].copy()
    output_df.to_csv(output_tsv, sep='\t', index=False)


if __name__ == '__main__':
    parser = ArgumentParser(description='Extract gene id to symbol mapping from annotation file, gtf or bedops styled bed.')
    parser.add_argument('-i', '--input', required=True, help='Path to the input bed file. Can be generated by "gtf2bed <genome.gtf >input.bed"')
    parser.add_argument('-t', '--type', choices=['gtf', 'bed'], default='gtf', help='Type of the input annotation file. Default is gtf.')
    parser.add_argument('-o', '--output', required=True, help='Path to save the output TSV file with two columns: gene_id and symbol.')
    args = parser.parse_args()
    main(args.input, args.type, args.output)
